require('plugins')

require('opts')

require('telescope-config')
require('lsp-config')
require('mason-config')
require('copilot-config')
require('cmp-config')
require('nerd-tree-config')
require('metals-config')
require('omnisharp-config')
require('treesitter-config')
require('lualine-config')
require('mappings')
